### ISSUE TITLE
Add superclass

### ISSUE THREAD

**Issue by cybersecrs** [cybersecrs/ripli#10]
@ml-dalos , I got error with frozen_string, so I pushed back old branch, with one more site, which use same functions as proxyscrape. If you want check it, if not I will do it based on your previous pull request.

edit: I think it's better way to scrap everything, then if needed export proxies with regexp, unless website is like proxyscrape, to get all list at once. That way ripli would work if website change some html/css (tell me if I'am wrong). We should test which way is faster, because with more sites added it will be more important.

**Comment by cybersecrs** [comment]
I made some mistakes while resolving conflict between branches, but I fixed it and it's merged. I still get error with optimist:
```
uninitialized constant Optimist (NameError)
```

**Comment by ml-dalos** [comment]
Are you sure that you have installed gem 'optimist'?

**Comment by cybersecrs** [comment]
Yea afinus work

sre, 7. okt 2020. 06.45 Alexey Lebedev <notifications@github.com> је
написао/ла:

**Comment by cybersecrs** [comment]
Where do you run it, what OS? But this code has nothing to do with OS

**Comment by ml-dalos** [comment]
During the merge "require 'optimitst'" was deleted from bin/ripli.rb
 https://github.com/cybersecrs/ripli/commit/c12387b9513fef6716fb708c70532dadc60efdaa#diff-e961354f95721027f5da36a369d5249d

**Comment by cybersecrs** [comment]
Dam... never again github on android... never. Thanks again, I will add
topics in next minutes. I closed issuse twice by accident, merged wrong
branch, and now removed optimist.

sre, 7. okt 2020. 07.29 Alexey Lebedev <notifications@github.com> је
написао/ла:

**Comment by cybersecrs** [comment]
Yea, I removed 'require' by mistake, now it work but do not recognize arguments, each time full list is downloaded.

**Comment by ml-dalos** [comment]
You must specify argument -t (--type)
'ruby bin/ripli.rb --type socks4'
if argument not specified used full list %w[https socks4 socks5]
Argument and optimist added for simplify future adding params, e.g by adding some param you can add ability to exclude scrapers, or start only specified scrapers, or set max response timeout for proxies and it's more convenient than try to parse ARGV

**Comment by cybersecrs** [comment]
It is more convenient, indeed. Works fine, I prepared tor with -t, will chage to --tor.

**Comment by cybersecrs** [comment]
It's not faster, but much better code and easier to extend.
